### ISSUE TITLE
Inclusão de testes para modelo User

### ISSUE THREAD

**Issue by ricardobsilva** [afilhodaniel/cinepolis_api#1]
Penso que poderiamos dar uma melhorada ao testar pelo menos as validações do model User. O que acha. @afilhodaniel ?

**Comment by afilhodaniel** [comment]
@ricardobsilva manda bala. Poderíamos atualizar tanto esse projeto como o projeto que eu usei como base, que é: https://github.com/afilhodaniel/rails_app

**Comment by ricardobsilva** [comment]
Boa!
