### ISSUE TITLE
cinepolisapi.heroku.com off

### ISSUE THREAD

**Issue by raphaelmro** [afilhodaniel/cinepolis_api#2]
bro, cinepolisapi.heroku.com está "offline".

**Comment by afilhodaniel** [comment]
Esta instância do Heroku é free, então é comum o link ficar offline algumas horas do dia. Tente acessar em outro momento, ou você pode subir o repositório pra algum servidor.

**Comment by afilhodaniel** [comment]
Opa!

Essa instância é a free do Heroku. É normal ela passar algumas horas do dia
fora do ar. Tente acessar em outro horário.

Mas esse link eu coloquei só pra demonstrar o código do repositório. Você
pode subir o código do repositório em qualquer outro server!

Abraços!

2016-10-21 1:14 GMT-03:00 Raphael Onofre notifications@github.com:

**Comment by raphaelmro** [comment]
Beleza, @afilhodaniel ! Obrigado!
